@startuml

left to right direction

!define QcloudPuml https://raw.githubusercontent.com/ServerlessBravo/qcloud-plantuml/release/v1.0/dist

!includeurl QcloudPuml/QcloudCommon.puml
!includeurl QcloudPuml/Qcloud_ServerlessCloudFunction.puml
!includeurl QcloudPuml/Qcloud_APIGateway.puml
!includeurl QcloudPuml/Qcloud_CloudObjectStorage.puml

Qcloud_ServerlessCloudFunction(EventFunction, "webapp", "Tencent", "Convert data into json format")
Qcloud_APIGateway(Gateway, "webapp", "Tencent", "Expose http/https protocols")
Qcloud_CloudObjectStorage(COS, "webapp", "Tencent", "Save users data as json")


Gateway ->  EventFunction: Trigger Function as user requests
EventFunction ->  COS: Save data into cos
EventFunction <-- COS: Save data successfully
Gateway <-- EventFunction: handle successfully

@enduml
